### PR TITLE
Renamed docs/StartHere.md to README.md for usability.

### PR DESCRIPTION
**Pull request by atombrella**
I find it slightly more intuitive that the overview is rendered by default under the files in Github.

### CODE REVIEW

**Comment by gniezen** [comment]
That's a good idea, thanks @atombrella ! Note that the same docs are made available at https://developer.tidepool.org/uploader/, if you prefer to read them in Gitbook.

Would you mind adding a comment on this PR to state you agree to the Tidepool Contributor License Agreement? See the following for how to go about doing this: https://developer.tidepool.org/contributors/

**Comment by atombrella** [comment]
Agreed :)

**Comment by gniezen** [comment]
Sorry to be a pain, but we need it in the following format:

> I agree to the terms of Tidepool Project’s Volunteer/Contributor License Agreement v1.1 as it exists at http://tidepool-org.github.io/files/TidepoolVCLA-1.1.pdf on <TODAY’S DATE>.

**Comment by atombrella** [comment]
I agree to the terms of Tidepool Project’s Volunteer/Contributor License Agreement v1.1 as it exists at http://tidepool-org.github.io/files/TidepoolVCLA-1.1.pdf on June 26th 2020.

**Pull request merged**
