### PR TITLE
[UPLOAD-809] cert update

### PR DESCRIPTION
**Pull request by krystophv**
Re: [UPLOAD-809] re-signs windows drivers with updated certificate. Minor updates to README instructions as I encountered hangups. 

[UPLOAD-809]: https://tidepool.atlassian.net/browse/UPLOAD-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gniezen** [comment]
@krystophv Thanks for the tip on using `Display Rich Diff`! Makes it so much easier. For removing the older drivers, I'll create a new PR against your branch.

**Comment by krystophv** [comment]
@gniezen I merged in your changes to drop the 7/8 drivers and re-signed with the most recent cert. Could you review the changes?

**Review by gniezen — DISMISSED** [review]
LGTM! :shipit:

**Comment by gniezen** [comment]
@krystophv I also signed them, lol. I guess it's good that we both know that our latest hardware tokens are working! :+1:

**Pull request merged**
