### PR TITLE
Saves Tandem binary blobs for debugging (UPLOAD-122)

### PR DESCRIPTION
**Pull request by gniezen**
Addresses [UPLOAD-122]. This also compresses all JSON binary blobs before sending them over the wire.

[UPLOAD-122]: https://tidepool.atlassian.net/browse/UPLOAD-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by gniezen** [comment]
Note: at the moment this is against the `electron-v16` branch until that branch is meged.

**Review by krystophv — APPROVED** [review]
LGTM :shipit:

**Comment by gniezen** [comment]
@krystophv Please give this one another look as there's been some changes since last review, and it's now passed QA.

**Review by krystophv — DISMISSED** [review]
Updates LGTM 👍🏼

**Pull request merged**
