### PR TITLE
Fix for Tandem uploads stalling (UPLOAD-290)

### PR DESCRIPTION
**Pull request by gniezen**
A fix related to [UPLOAD-290]. 

[UPLOAD-290]: https://tidepool.atlassian.net/browse/UPLOAD-290

### CODE REVIEW

**Comment by gniezen** [comment]
This is in draft until we have an affected user that can run the test version.

**Review by pazaan — APPROVED** [review]
LGTM! 🚢

**Comment by gniezen** [comment]
Passed QA, removed test suffix. Ready for final review.

**Review by pazaan — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
