### PR TITLE
Add Operating System property to KissMetrics events (UPLOAD-766)

### PR DESCRIPTION
**Pull request by gniezen**
Addresses [UPLOAD-766].

[UPLOAD-766]: https://tidepool.atlassian.net/browse/UPLOAD-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krystophv — APPROVED** [review]
LGTM :shipit:

**Review by krystophv — APPROVED** [review]
Updates LGTM 👍🏼

**Comment by gniezen** [comment]
@krystophv I changed from suing ua-parser to using the UA Client Hints API instead.

**Review by krystophv — APPROVED** [review]
Update looks good to me. 👍🏼

**Comment by gniezen** [comment]
@krystophv Some minor changes since your last review. Mind having a quick look?

**Review by krystophv — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
