### PR TITLE
Add support for Control-IQ (UPLOAD-292)

### PR DESCRIPTION
**Pull request by gniezen**
Addresses [UPLOAD-292].

[UPLOAD-292]: https://tidepool.atlassian.net/browse/UPLOAD-292

### CODE REVIEW

**Review by krystophv — DISMISSED** [review]
LGTM :shipit:

**Review by krystophv — APPROVED** [review]
Changes LGTM 👍🏼

**Comment by gniezen** [comment]
@krystophv This still needs a final round of code review of the latest changes.

**Review by krystophv — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
