### PR TITLE
Fixes for time update messaging (UPLOAD-1201, UPLOAD-1157)

### PR DESCRIPTION
**Pull request by gniezen**
Addresses [UPLOAD-1201] and [UPLOAD-1157].

[UPLOAD-1201]: https://tidepool.atlassian.net/browse/UPLOAD-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UPLOAD-1157]: https://tidepool.atlassian.net/browse/UPLOAD-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krystophv — DISMISSED** [review]
LGTM 💯

**Review by krystophv — DISMISSED** [review]
LGTM 💯

**Comment by vojtech-cerveny** [comment]
@gniezen, `build-macos` check fails and it is required to merge. Can you check it what's wrong please? 

It seems that github already have this asset, if I get it right. 

From log:  
```
Failed Task: build
Stack Trace: HttpError: 422 Unprocessable Entity

Method: POST
URL: https://uploads.github.com/repos/tidepool-org/uploader/releases/150421733/assets?name=Tidepool%20Uploader-2.57.0-time-message-fix.2-mac.zip.blockmap

Data:
{
  "message": "Validation Failed",
  "request_id": "C1A7:368889:27CDF3:2C0534:66686CB9",
  "documentation_url": "https://docs.github.com/rest",
  "errors": [
    {
      "resource": "ReleaseAsset",
      "code": "already_exists",
      "field": "name"
    }
  ]
}
```

**Comment by gniezen** [comment]
@vojtech-cerveny There's a [bug in electron-builder ](https://tidepool.atlassian.net/browse/UPLOAD-544) that hasn't been fixed for years. Unfortunately there's nothing that we can do about it, so the workarounds are:

- bump the version number to create a new build that doesn't have existing assets
- delete the assets and trigger the build again

I just did the second one. Keep in mind that this PR cannot be merged even though [UPLOAD-1201] has been approved, as [UPLOAD-1157] is also linked to this PR and still needs to be tested.

**Review by krystophv — APPROVED** [review]

**Pull request merged**
