### PR TITLE
Add link to Omnipod support article for macOS uploads that fail because of removable volumes permissions (UPLOAD-789)

### PR DESCRIPTION
**Pull request by gniezen**
Addresses [UPLOAD-789].

[UPLOAD-789]: https://tidepool.atlassian.net/browse/UPLOAD-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krystophv — DISMISSED** [review]
LGTM 🚀

**Comment by gniezen** [comment]
@krystophv Please have a look at the changes since the last review :pray:

**Review by krystophv — DISMISSED** [review]
Updates LGTM 🚀

**Review by krystophv — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
