### PR TITLE
Auto-update of time on Bluetooth meters (UPLOAD-236)

### PR DESCRIPTION
**Pull request by gniezen**
Addresses [UPLOAD-236].

[UPLOAD-236]: https://tidepool.atlassian.net/browse/UPLOAD-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by krystophv — APPROVED** [review]
LGTM 🚀

**Review by krystophv — DISMISSED** [review]
Updates LGTM 💯

**Comment by gniezen** [comment]
@krystophv Another small update to fix an issue found during testing.

**Review by krystophv — APPROVED** [review]
Updates LGTM 🚀

**Comment by gniezen** [comment]
@krystophv Yet another review of this one, please :)

**Review by krystophv — DISMISSED** [review]
Latest update LGTM 🚀

**Pull request merged**
